version: "3.9"

services:

  # my test app
  app:
    build: app
    command: "sh delay.sh"
    depends_on: 
      - db

  # arangodb, exposes port 8529
  db:
    image: arangodb:latest
    ports:
      - "8529:8529" # publishing the port to host so you can use the web interface
    environment:
      - ARANGO_NO_AUTH=1
        #volumes:
        #- "${PWD}/db:/var/lib/arangodb3" # for persistance
