version: "3.9"

services:

  app:
    build: app

  # arangodb, exposes port 8529
  db:
    image: arangodb:latest
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - "${PWD}/db:/var/lib/arangodb3"

networks:
  default:
